### ISSUE TITLE
[Epic](infra) Infrastructure Deployment and Provisioning

### ISSUE THREAD

**Issue by andypf** [cloudoperators/juno#102]
1.  Juno Repo Refactoring
     - [x] #52  
     - [x] #103 
     - [x] #104 
     - [x] #105 
     - [x] #172 
     - [x] #265
2. Greenhouse, serve all MFEs locally (All-in-one)
    - [x] https://github.com/cloudoperators/greenhouse/issues/352
3. Supernova, create standalone version (independant of Greenhouse)
    - [x] https://github.com/cloudoperators/greenhouse-extensions/issues/296
    ---
4.  Decomission Asssets Server and use colocated assets strategy
    - [ ] adapt elektra Pipeline to pull dashboard App and bundle and host in elektra
    - [ ] whois ?
    - [ ] volta ?
5.  Monorepo Elektra
    - [ ] Create new Repo elektra 
    - [ ]  turorization (Turborepo)
6.  Host App Architecture/Generator
    - [ ] add package to juno (toolbox)
    - [ ] Implement App Generator
7.  Elektra API Architecture
