### ISSUE TITLE
[TASK]:  @cloudoperators/juno-ui-components storybook upgrade from 7.x.x to 8.x.x

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#160]
**Task Description**
We need to do an ugrade of storybook version, check first which preparation need to be done

**Sub-tasks**

- [x] Do upgrade in packages json
- [x]  See breaking changes
- [ ] Solve if it is a breaking change, do upgrade
- [x] Our self-developed plugin for theme switching doesn't work out of the box with v8.x and needs to be fixed

**Additional Context**
Please have a look for the info here:
[Storybook migration guide
](https://storybook.js.org/docs/migration-guide)
