### ISSUE TITLE
[TASK]: Convert @cloudoperators/juno-url-state-provider to TypeScript

### ISSUE THREAD

**Issue by TilmanHaupt** [cloudoperators/juno#163]
### Task Description

We need to convert  @cloudoperators/juno-state-provider to TypeScript

**Sub-tasks**

- [ ] Integrate Lint with typescript config(look to juno-communicator package as example)
- [ ] Integrate tsconfig.json from config package
- [ ] Integrate vitest for testing
- [ ] Integrate tsup for bundling things up
- [ ] Delete old rollup/esbuild/babel
- [ ] Makes tests green integrate in example app.
- [ ] Update readme

**Related Issues**
- #119 

**Additional Context**
Look to already existing configuration in juno-communicator
