### ISSUE TITLE
[EPIC]: @cloudoperators/juno-ui-components migrate UI Components to TypeScript

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#168]
# Epic: @cloudoperators/juno-ui-components to TypeScript

## Description

Transition all components, and files from JavaScript to TypeScript to enhance code quality and maintainability. This epic will focus on ensuring a smooth migration with minimal disruption.

## Goals
- #161 
- Convert all JavaScript components to TypeScript
- Convert all tests to TypeScript
- Delete rollup and use tsup for bundling.
- Include types into package bundle

## Benefits

- Improved type safety and code clarity
- Better developer experience with enhanced tooling
- Early error detection through static type checking

## Tasks

- [x]  #161 
- [x] #583
- [x] https://github.com/cloudoperators/juno/issues/645
- [x] https://github.com/cloudoperators/juno/issues/662
  - [x] #225
  - [x] #226
- [x] Convert group of components, inlcuding tests to TypeScript in this order:
  - [x] #212
  - [x] #213
  - [x] #214
  - [x] #215
  - [x] #217
  - [x] #218
  - [x] #219
  - [x] #222
  - [x] #220
  - [x] #221
  - [x] #223
  - [x] #224
  - [x] #227
  - [x] #228
  - [x] #229
  - [x] #230
  - [x] #231
  - [x] #232
  - [x] #233
  - [x] #234
  - [x] #235
  - [x] #236
  - [x] #237
  - [x] #238
  - [x] #239
  - [x] #240
  - [x] #241
  - [x] #242
  - [x] #243
  - [x] #244
  - [x] #245
  - [x] #246
  - [x] #247
  - [x] #248
  - [x] #249
  - [x] #250
  - [x] #251
  - [x] #252
  - [x] #253
  - [x] #254
  - [x] #255
  - [x] #256
  - [x] #257
  - [x] #258
  - [x] #259
  - [x] #260
  - [x] #261
  - [x] #262
  - [x] https://github.com/cloudoperators/juno/issues/665
  - [x] #263 
- [x] https://github.com/cloudoperators/juno/issues/605
- [ ] Export all component types https://github.com/cloudoperators/juno/issues/604
- [ ] Update documentation to reflect TypeScript usage for each package

## Acceptance Criteria

- All components in the components folder are successfully converted to TypeScript
- Build and deployment pipelines compile and deploy TypeScript code without issues
- Updated documentation and guidelines for contributing TypeScript code are available
- All tests and lint pass with TypeScript integration for each package

**Comment by guoda-puidokaite** [comment]
All improvements and inconsistencies found during the migration have been documented here: https://github.com/cloudoperators/juno/issues/570.
