### ISSUE TITLE
[TASK]: convert @cloudoperators/juno-messages-provider to typescript.

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#170]
### Task Description

We need to convert message provider to typescript

**Sub-tasks**

- [ ] Integrate Lint with typescript config
- [ ] It uses UI components
- [ ] Integrate tsconfig
- [ ] Integrate vitest for testing
- [ ] Integrate tsup for bundling things up
- [ ] Delete old rollup/esbuild/babel
- [ ] Makes tests green integrate in example app.

**Related Issues**
- #119 

**Additional Context**
Maybe we need to migrate usable UI components to typescript first before we start this issue look to epic #162

**Comment by andypf** [comment]
This issue is a duplicate : 
- #198
