### ISSUE TITLE
[TASK]: Convert @cloudoperators/juno-oauth to typescript

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#171]
### Task Description

We need to convert juno-oauth to typescript

**Sub-tasks**

- [ ] Integrate Lint with typescript config
- [ ] Integrate tsconfig
- [ ] Integrate vitest for testing
- [ ] Integrate tsup for bundling things up
- [ ] Delete old rollup/esbuild/babel
- [ ] Makes tests green integrate in example app.
- [ ] Update readme

**Related Issues**
- #119 

**Additional Context**
