### ISSUE TITLE
[TASK]: Migrate K8s client to @cloudoperators/juno-k8s-client and to TypeScript

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#197]
### Task Description

We need to migrate and convert k8s client under @cloudoperators/juno-k8s-client to TypeScript

**Sub-tasks**
- [x] MIgrate the codebase to package inside of juno repo
- [ ] Integrate Lint with typescript config(look to juno-communicator package as example)
- [ ] Integrate tsconfig.json from config package
- [x] Integrate vitest for testing
- [x] Integrate tsup or vitest for bundling things up
- [x] Delete old rollup/esbuild/babel
- [ ] Makes tests green integrate in example app.
- [x] Update readme

**Related Issues**
- #119 

**Additional Context**
Look to already existing configuration in juno-communicator

**Comment by barsukov** [comment]
Duplicated isseu 
https://github.com/orgs/cloudoperators/projects/4/views/1?pane=issue&itemId=66836614
