### ISSUE TITLE
[TASK]: Template(create a turbo generator for pacakges based on typescript

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#199]
### Task Description

We need to crate a generator that going to help easily setup the new package with predefined options. Using the codemode.

**Sub-tasks**

- [x] Integrate Lint with typescript config(look to juno-communicator package as example)
- [x] Integrate tsconfig.json from config package
- [x] Integrate vitest for testing
- [x] Integrate tsup or vite for bundling things up
- [x] Delete old rollup/esbuild/babel
- [x] Makes tests green integrate in example app.
- [x] Update readme

**Related Issues**
- #119 

**Additional Context**
Look to already existing configuration in juno-communicator
