### ISSUE TITLE
[TASK]: Sunset @cloudoperators/juno-utils

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#202]
We want to decomission this and move the exported functions/hooks to other places.

### Task Description

So first we will move useEndlessScrolList under packages/ui-components/hooks directory.
Second we need to replace ApiMock logic with faker.js if and where it is necessary.

**Sub-tasks**

- [ ] Transfer hook under ui-components
- [ ] Rewrite hook to typescript
- [ ] Replace hook usage on all apps(doop, heureka, example, supernova)
- [ ] Delete MockApi logic and replace it with faker.js where it is necessary
- [ ] Delete library Juno-utils
