### ISSUE TITLE
[Task](k8s-client): Enable lint rulles back

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#206]
**Task Description**
Cause of the migration to typescript we have to disable bunch of rules:
```
 // TODO: We need to make all of this checks on again, step by step
    rules: {
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-floating-promises": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/unbound-method": "off",
    },
```
**Sub-tasks**

- [ ]  "@typescript-eslint/no-unsafe-assignment": "off",
- [ ]  "@typescript-eslint/no-unsafe-call": "off",
- [ ]  "@typescript-eslint/no-unsafe-argument": "off",
- [ ]  "@typescript-eslint/no-floating-promises": "off",
- [ ]  "@typescript-eslint/no-unsafe-member-access": "off",
- [ ]  "@typescript-eslint/unbound-method": "off",

**Related Issues**
#205  
**Additional Context**
This changes could involve addtional refactoring.
