### ISSUE TITLE
[TASK](ui): Migrate DataGrid component to TypeScript

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#224]
### Task Description

We need to convert Button and all related components from @cloudoperators/juno-ui-components to TypeScript

**List of potential dependencies**

- DataGrid, DataGridCell, DataGridCheckboxCell, DataGridFoot, DataGridHeadCell, DataGridRow, DataGridToolbar

**Sub-tasks**

- [ ] change the name to .tsx of all related components
- [ ] Change the stories to .tsx and all related componetns
- [ ] fix all errors related to npm run typecheck
- [ ] Transfer all related tests to vitests from jest
- [ ] Check if npm run build is working and prove the working parts in storybook or example app
- [ ] Check that npm run lint is working correctly and fix all tslint errors

**Related Issues**
- #168 

**Additional Context**
Please check this online codemode editor to change the PropTypes to a proper Ts interfaces

https://github.com/mskelton/ratchet
Online editor: https://ratchet.mskelton.dev/

We need to be pretty concious about migration to ts cause it could create a potential breaking changes. Also if there will be too much changes at once maybe consider to split up the task again. Also some dependencies could be hidden and only discovered while executing the migration, could also lead to potential reconsidering the order of task execution.
