### ISSUE TITLE
[Task](greenhouse): Migrate SuperNova into Juno

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#298]
**Task Description**

Migrate Supernova app from https://github.com/cloudoperators/greenhouse-extensions to `apps/supernova`

Look into **example** app and implement tasks like
- build
- dev
- eslint
- later on Typescript
- later on vitest for tests.

**Sub-tasks**

- [x]  Create a simple app(Plain copy and to run it smoke test) #305
- [x]  Check the current build system and if it will be possible to run as it is under build export #305
- [x]   Clean up all lint errors #312
- [ ]  Later on check if it is possible to run with vite
- [ ] Adapt pipeline(asset server) and manifest update.
- [x] Migrate image workflow #314
- [x] Trigger the image workflow when the supernova version (in package.json) has changed #318
- [x] README #334 #340
- [ ] Do not delete the old one(1 year)

**Related Issues**
#297
