### ISSUE TITLE
[Task](ui): fix all lint errors from supernova which are disabled

### ISSUE THREAD

**Issue by ArtieReus** [cloudoperators/juno#312]
**Task Description**
Fix all lint errors from supernova which are disabled.

**Sub-tasks**

- [x] Remove rules from eslint.config.mjs
- [x] Run from apps/supernova `eslint.config.mjs`
- [x] Fix all errors

**Related Issues**
Link to related issues or tasks, if any.

**Additional Context**
Add any other context or information here.
