### ISSUE TITLE
[Task](greenhouse):  Migrate Doop into Juno

### ISSUE THREAD

**Issue by ArtieReus** [cloudoperators/juno#346]
**Task Description**

Migrate Doop app from https://github.com/cloudoperators/greenhouse-extensions to apps/supernova

Look into **example** app and implement tasks like
- build
- dev
- eslint
- later on Typescript
- later on vitest for tests.

**Sub-tasks**

- [x]  Create a simple app(Plain copy and to run it smoke test) 
- [x]  Check the current build system and if it will be possible to run as it is under build export
- [x]   Clean up all lint errors

**Related Issues**
#297
