### ISSUE TITLE
[Task](greenhouse): Migrate Heureka into Juno

### ISSUE THREAD

**Issue by ArtieReus** [cloudoperators/juno#347]
**Task Description**

Migrate Heureka app from https://github.com/cloudoperators/greenhouse-extensions to apps/heureka

Look into **example** app and implement tasks like
- build
- dev
- eslint

**Sub-tasks**

- [x]  Create a simple app(Plain copy and to run it smoke test) 
- [x]  Check the current build system and if it will be possible to run as it is under build export
- [x]   Clean up all lint errors

**Related Issues**
#297
