### ISSUE TITLE
[Task](supernova): Make initialFilters configurable as props

### ISSUE THREAD

**Issue by edda** [cloudoperators/juno#368]
**Task Description**
Supernova allows the setting of initial filters. Currently this is only used for setting the user's support group as an initial filter. This needs to be generalized so that arbitrary filters can be initially active. These filters must be passable to Supernova via prop and readable from a config in the case of standalone deployment.

**Sub-tasks**

- [ ] Read initial filters from props. 
  - Variable name: `initialFilters`
  - Example:
  ```
   "initialFilters": {
     "support_group": ["containers"],
    }
  ```
- [ ] Read user name from props
  - Variable name: `username`
  - Example:
  ```
   "username": "A Reuschenbach Puncernau"
  ```
- [ ] Make initial filters configurable from env in standalone deployment

**Related Issues**
Link to related issues or tasks, if any.

Related Epic
#275
