### ISSUE TITLE
[EPIC](supernova): Alerts UI features and refactoring for general use

### ISSUE THREAD

**Issue by edda** [cloudoperators/juno#369]
There are various features that we want to add to the alerts UI. Additionally there are some areas where the app needs to be generalized and/or made configurable so that it becomes more usable in diverse landscapes.

Features:
- [x] cloudoperators/juno#370 
- [x] cloudoperators/juno#371 
- [ ] Number previously expired silences of a altert
- [x] cloudoperators/juno#372
- [x] cloudoperators/juno#373
- [x] cloudoperators/juno#374
- [x] cloudoperators/juno#375 
- [x] cloudoperators/juno#376   
- [x] cloudoperators/juno#378 
- [x] cloudoperators/juno#379 
- [x] https://github.com/cloudoperators/juno/issues/335
- [x] https://github.com/cloudoperators/juno/issues/384
- [x] cloudoperators/juno#401

Generalizations: 
- [x] cloudoperators/juno#381  
 

**Sprint 24.10:**
- [x] #368 
- [x] #422 
- [x] #474

**Comment by ArtieReus** [comment]
moved the last two tasks to following epic #621
