### ISSUE TITLE
[Task](ci): PR preview of packages heureka and doop

### ISSUE THREAD

**Issue by ArtieReus** [cloudoperators/juno#398]
**Task Description**  
Extend multi-app deployments that enable previewing the current state of the PR on GitHub Pages when changes are made to `heureka` and `doop`.

**Sub-tasks**  
- [ ] Reuse a standalone `index.html` file for both Docker and GitHub Actions workflows.
- [ ] Retrieve `appProps` from GitHub Secrets instead of hardcoding them in the codebase.
- [ ] Extend the workflow to deploy a preview to GitHub Pages for both `heureka` and `doop` if changes are detected in both apps.

**Related Issues**
Link to related issues or tasks, if any.

**Additional Context**
Add any other context or information here.
