### ISSUE TITLE
[Task](build): migrate from esbuild to vite 

### ISSUE THREAD

**Issue by andypf** [cloudoperators/juno#400]
## Task Description

To maintain consistency and address dependencies on Babel, Jest, and other libraries, we aim to migrate from esbuild to Vite with this task.

### Sub-tasks

- [x] Find a way to migrate esbuild along with all its plugins to Vite.
- [x] Migrate all packages and applications currently using esbuild to Vite.
- [x] Thoroughly test everything.

**Comment by andypf** [comment]
we migrated the example app to vite/vitest
