### ISSUE TITLE
[TASK](greenhouse): Migrate to vite/vitest

### ISSUE THREAD

**Issue by andypf** [cloudoperators/juno#429]
**Task Description**

This task involves migrating the current build and testing system to Vite and Vitest. The goal is to unify the build system across the whole juno repo.

**Sub-tasks**

- [ ] rename `.js` to `.jsx`
- [ ] migrate from esbuild to vite (see example app)
- [x] migrate from jest to vitest (see example app)

**Related Epic**
- #348

**Comment by barsukov** [comment]
I would ignore this package if it will be to painful to migrate... cause we will generate carbon where we will implement everything here.
