### ISSUE TITLE
[EPIC](carrier): POC and implementation MFE carrier app

### ISSUE THREAD

**Issue by edda** [cloudoperators/juno#43]
Implement MFE carrier app according to decided architecture.

- [ ] POC: carrier as next.js app
- [ ] Generalize Greenhouse all-in-one deployment
- [ ] Create carrier app v1.0
- [ ] check how to catch runtime errors from embedded apps

### Requirements

- [ ] Carrier app should be very conscious of memory consumption. Rather try to dynamically load only what is currently needed

**Comment by andypf** [comment]
obsolete, please refer to 
- #386
