### ISSUE TITLE
Integrate vite Greenhouse Admin Apps if needed depending on the design decision

### ISSUE THREAD

**Issue by andypf** [cloudoperators/juno#430]
**Task Description**

This task involves migrating the current build and testing system to Vite and Vitest. The goal is to unify the build system across the whole juno repo.

**Sub-tasks**

- [ ] rename `.js` to `.jsx`
- [ ] migrate from esbuild to vite (see example app)
- [ ] migrate from jest to vitest (see example app)

**Related Epic**
- #348

**Comment by andypf** [comment]
Closing this issue as it is a duplicate of 
- #429
