### ISSUE TITLE
[TASK](messages-provider): Migrate to vite/vitest

### ISSUE THREAD

**Issue by andypf** [cloudoperators/juno#443]
**Task Description**

This task involves migrating the current build and testing system to Vite and Vitest. The goal is to unify the build system across the whole juno repo.

**Sub-tasks**

- [ ] rename `.js` to `.jsx`
- [ ] migrate from esbuild to vite (see example app)
- [ ] migrate from jest to vitest (see example app)

**Related Epic**
- #348
