### ISSUE TITLE
[TASK](utils): Sunset of juno-utils 

### ISSUE THREAD

**Issue by andypf** [cloudoperators/juno#446]
**Task Description**

This task involves migrating the current build and testing system to Vite and Vitest. The goal is to unify the build system across the whole juno repo.

**Sub-tasks**

- [ ] useInfiniteScroll to ui-components hook and change imports
- [ ] FakerJS instead of Mockk
- [ ] DO NOT FORGET ELECTRA APP
- [ ] delete package
- [ ] Notify people who could possibly use it
**Related Epic**
- #348

**Comment by barsukov** [comment]
Maybe we need to decomission this one moving one hook under ui-components and other part probably could be just deleted or changed to faker.js inside the greenhouse project...
