### ISSUE TITLE
[EPIC](Typescript): Transfer all apps to typescript with ts-migrate

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#451]
### Description
We will migrate our apps with typescript here with a codemode. So eliminate all problems later.
[Typescript migration
](https://medium.com/airbnb-engineering/ts-migrate-a-tool-for-migrating-to-typescript-at-scale-cd23bfeb5cc)
### Objectives

List the high-level objectives or goals of this epic.

- Example App
- Heureka
- Doop
- Supernova

Greenhouse Dashboard will be out of scope cause we decided to replace it with carbon. Also template will be regenerated with vite so we will not need it here.

### Acceptance Criteria

Define the criteria that must be met for this epic to be considered complete.

- [x] Fully transfer app to typescript. 
- [x] Build system should be on vite.
- [x] All javascript should be eliminated.

### Tasks

- [ ] Example app transfer
- [ ] Doop app transfer with codemode
- [ ] Heureka app transfer

### Dependencies

Identify any other epics, issues, or tasks that this epic depends on.

- #428 
- #424 
- #429
- #431 

### Additional Notes

Any additional information, context, or considerations.
