### ISSUE TITLE
[Task](template): Generate new Template app

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#452]
**Task Description**
We will use this template to generate first our tempalte app that we will use to start carbon project:
https://github.com/joaopaulomoraes/reactjs-vite-tailwindcss-boilerplate
**Sub-tasks**

- [ ] rename template app to oldTemplate
- [ ] Generate new one and test that it works
- [ ] Integrate necessary componetns
- [ ] Check if it works with our setup and integrate to turbo
- [ ] Update Readme how to use it

**Related Issues**
This could be a potential blocker for generating new carbon project so we should make it possible as fast as we can.

**Additional Context**
Add any other context or information here.
