### ISSUE TITLE
[EPIC](greenhouse): Carbon App Dashboard implementation

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#475]
### Description

We need to rewrite the greenhouse dashboard with a new standard including typescript, vite, vitests and whole architecture should be changed.

### Objectives

List the high-level objectives or goals of this epic.

- [ ] Carbon App 
- [ ] Include all functionality of original Dashboard
- [ ] Deletion of old App

### Acceptance Criteria

Define the criteria that must be met for this epic to be considered complete.

- [ ] The app should have all turbo related tasks
- [ ] It should look and feel same way as original dashboard
- [ ] After completion we should rename it to a Greenhouse and delete the old one.
- [ ] Deployment and release process should be impelemented.

### Tasks

Break down the epic into smaller, actionable tasks or user stories. Bigger tasks should be issues themselves.

- [ ] - Generate new App
- [ ] - Integrate react-router(or wouter?)
- [ ] - Implement org-view
- [ ] - Implement cluster-view
- [ ] - Implement team-view
- [ ] - Implement plugins-view
- [ ] - Implement secrets-view

### Dependencies
Identify any other epics, issues, or tasks that this epic depends on.

- Template App should be implemented
- Old Greenhouse should still have bugfixes

### Additional Notes

Any additional information, context, or considerations.
