### ISSUE TITLE
TASK(greenhouse): Generate new Carbon app using template app and turbo

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#476]
**Task Description**
We need to generate new App with name carbon

**Sub-tasks**

- [ ] Generate using turbo generator and template app
- [ ] Integrate to build pipeline 
- [ ] Docker and release process

**Related Issues**
Link to related issues or tasks, if any.

**Additional Context**
Add any other context or information here.
