### ISSUE TITLE
[SPIKE](Carbon): Carbon research routing task

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#505]
**Task Description**
We need a research a routing redesing for our new router:

**Sub-tasks**

- [x] Requirements and concept how we want the url looks like
- [ ] Edgecase coverage and real testing
- [ ] integrate extentions and modules
- [ ] Check how we will treat subApps
- [ ] Keep Iframe integration of cockpit in mind
- [ ] It is a breaking change need to be proper documented

This tasks are not required to be closed at once but result of this TAsk should be a good Proposal document with a working MVP concept under Carbon dashboard directory.
