### ISSUE TITLE
[TASK](ui): rework Menu to become PopupMenu

### ISSUE THREAD

**Issue by franzheidl** [cloudoperators/juno#529]
**Task Description**
The current Menu (and ContextMenu) component is flawed in several ways, and needs to be reworked as a more general `PopupMenu` component.

The new `PopupMenu` component should expose `PopupMenu.Toggle`, `PopupMenu.Menu`, `PopupMenu.Item` and `PopupMenu.Section` subcomponents.

The new `PopupMenu` component should accept a `toggle` and a `menu` as ~~props children. It should be possible to pass these as slotted props, or as~~ children:

```
<PopupMenu>
  <MyToggle />
  <MyMenu />
</PopupMenu>
```

Users can use subcomponents as exposed by `PopupMenu` (recommended), or their own custom components as `toggle` and `menu` respectively.

```
<PopupMenu>
  <PopupMenu.Toggle />
  <PopupMenu.Menu>
    <PopupMenu.Item />
  </PopupMenu.Menu>
</PopupMenu>
```

## Additional Requirements
* Both `toggle` and `menu` should be optional, resulting in the component rendering always.
* When no `toggle` is passed, `PopupMenu` should render an "overflow" / "kebap" icon as a toggle, allowing it to effectively replace the curren t`ContextMenu` component
* When no `menu` is passed, the toggle should still render and all necessary events should fire anyways, even when there is no menu to show.
* When passing children to the `PopupMenu`, the bevaviour should be as follows:
  * When subcomponents are being used, we render according to type / element, regardless of sequence (edge case: more than one `PopupMenu` and/or `PopupMenu.Menu` each: render the first one met, ignore the rest)
  * Clicking outside an open menu should close the menu

**Sub-tasks**

- [x] Create a new component in TS as a generic `PopupMenu`
- [x] Design a component architecture that wraps Headless Menu
- [x] Use sub components
- [x] Use the new PortalProvider to render the Menu into
- [x] Figure out and implement working, reliable positioning of the menu in the Portal
- [x] Make component render as an overflow menu per default, effectively replacing ContextMenu
- [x] Allow passing any Juno icon instead of default three vertical dots icon
- [x] Make sure all onClick handlers on custom component toggle still run
- [x] Allow passing the toggle as a child
- [x] Allow passing the menu as a child
- [x] Deprecate current Menu and ContextMenu components 
- [x] Make sure menu closes on click outside
- [x] Allow for rendering items as `div` or `anchor` 
- [x] Implement `PopupMenu.Section` ~~via Headless U menu `Section`~~
- [x] Implement `PopupMenu.SectionHeading` ~~via Headless UI menu `Heading`~~
- [x] Implement `PopupMenu.Separator` ~~via Headless UI menu `Separator`~~

**Related Issues**
**DONE:** Will require migration of `Menu` and related `MenuItem`, `MenuSection` components to TypeScript #237  

-

**Comment by franzheidl** [comment]
The intended flexibility in terms of API and usage as outlined above leads to a large amount of complexity in the component, especially accepting any kind of component as a toggle and potentially menu, as well as allowing to pass them as children or as slotted props. Also, there will be edge cases, some of which may prove impossible to handle nicely.

Current WIP is on https://github.com/cloudoperators/juno/tree/popupmenu-529

(This does not yet cover rendering children properly, and already is a very large, complex component)

I am currently considering cutting some requirements and building a thin wrapper around headless ui menu first, and then see how well this works for our users and address shortcomings or requirements for additional functionality and features later.

**Comment by franzheidl** [comment]
A **WiP** alternative, much simpler implementation of a `PopupMenu` component as a thin wrapper around headless ui menu can be found here: https://github.com/cloudoperators/juno/tree/popupmenu-simple-529

This does not have any styling yet, but is helpful in understanding why this component is difficult to build:

When just wrapping headless ui menu, there is no way of passing an `open` prop, as headless ui menu manages its state internally and does not expose such a functionality. If we want to allow for passing an open prop, and there is a strong argument to do that for the sake of consistency in our system, we would need to override headless ui's internal state with our own, and render the menu as `static`. Th edownside of this approach is we would loose a lotof headless-ui menu's inbuilt functionality, e.g. clsoing the menu on clicking outside or clicking an item would need re-implementing in our component.

**Comment by franzheidl** [comment]
`Section`, `SectionHeading` and `SectionSeparator` have been implemented, but without using Headless UI menu's subcomponents, as Headless UI Menu does not expose these before version 2.0.0. ( we are on v1.7.19 at the time of writing).

We will do the upgrade to headless-ui react v2 in a seperate taks, as a couple of our most complex componenents like ComboBox and Select will be affected.

The current implementation will allow for upgrading to headless ui v2 without changes/breaking.

**Comment by edda** [comment]
Closing this issue. Will open a new issue for the Headless UI upgrade to v2.*
