### ISSUE TITLE
[Task](exampleapp): Rework the example app according to the new design guidelines

### ISSUE THREAD

**Issue by edda** [cloudoperators/juno#594]
**Task Description**
Rework the existing example app, ensuring it follows the guidelines outlined in the design document. This will serve as a real-world test of how easily developers can adopt and implement the design system. 

**Sub-tasks**

- [x] Fix exisiting exampleapp content following the guidelines 
  - **Update**: Further work in https://github.com/cloudoperators/juno/issues/803
- [x] Expand app with additional components or pages where necessary (to use as many of our standard patterns/components as is feasible). Get in touch with @franzheidl with questions regarding this point.
- [x] Collect feedback to design guidelines, particularly where things are hard to understand, information that needs to be highlighted so its harder to miss, etc.

**Additional Context**
The idea is to try to improve the example app following the guidelines so that it can act as a reference implementation of said guidelines. The additional goal of this task is to get feedback on this first version of the guidelines document to be able to improve it.

**Comment by guoda-puidokaite** [comment]
**Update**

I’ve added a [comment](https://www.figma.com/proto/dPqygpJx9EmHYeYVC3mZGU?node-id=0-544#1146498299) to the 'Juno Design System Documentation', explaining that in order for the outlined guidelines to be successfully implemented in the Example App, we need wireframes/mockups. They would help us envision and plan a full website, bridging the gap between theory and implementation.

In the interim, I shared my current progress/ideas with Franz on how the Example App could be improved and gathered his insights.

We agreed that making significant changes without a wireframe/mockup design would be inefficient, but agreed on some initial changes that could already be implemented.

**Agreed Upon Actions:**
- Title: Update to new branding.
- User Info and Logout Button: Use a popup menu once the profile is clicked, revealing the logout button.
- Top Level Navigation: It currently doesn’t work. Make it functional for the current page, update the title. Additional options need design input.
- Breadcrumbs: Currently don’t work. Leave as is, need real-life use cases and design input.
- Tabs: Leave as is. The second tab especially needs design input, which is currently serving as a “playground”, rather than app content.
- Peak Actions:
    - “Add a Peak”: Use a modal for peak creation, instead of a side panel.
    - “Edit Peak”: Leave as is, a side panel.
    - “Delete Peak”: (New) Add modal with deletion warning.
    - “Open In New Tab”: Leave as is.
    - Further improvements need design input e.g. showcasing what components should be used when items need to be compared. Best use of modal vs. side panel etc.
- (New) Detailed Item View: When a data grid item is clicked, show a detailed view with initial placeholder content e.g. header, data table etc. This page needs design input.
- (New) Footer: Add a footer with basic copyright/licensing information. Further improvements need design input. We also need to investigate how this component can support this info better in the future.
- "404, Not Found" Error: After some time of using the app, this error appears. We need to make it non-technical/user friendly, identify its cause and resolve it.
- App Crash: After some time of using the app, the app crashes. We need to identify the cause and resolve it.
- URL parameters: The URL parameters are ambiguous, paths seem to work. Could be related to app crash, need to investigate. 
- Documentation: Leave as is for now. Once we have a designed example app with sound reasoning, we should improve the documentation to explain choices to the user e.g. why we chose a Panel instead of Modal etc. to enhance understanding and give ideas of options.

**Discussed Future Collaboration:**
- Understanding user needs and designing the example app around actual use cases and app content is crucial to help retain semantic meaning and help the user understand how to use the Example App.
- It would be extremely helpful to establish a continuous feedback loop between the design and development teams:
    - Early developer involvement in the design process would provide valuable feedback, helping identify needs and potential issues. 
    - Ongoing developer feedback on existing designs and Juno components would highlight what works and what can be improved.
    - Designer involvement in review of developed apps would help enhance overall UX, quality of apps and help future learning.

Thank You, @franzheidl for the collaboration.

CC: @edda

**Comment by guoda-puidokaite** [comment]
**Update:**

- Decided to move away from fixing functionality (as discussed in previous comment) and **focus on showcasing Juno UI frontend capabilities and improving the UX**. Some functionality won't work, if not important to the goal. 
- Re-designed and developed a proposal for an Example App, as a standard:
  - Reviewed existing apps to gather most important use cases/patterns and re-designed + implemented an Example App around them.
  - Reviewed UX of existing apps, found patterns that can be improved and implemented them.
  - Included a Detail Page, as suggested above.
  - Used useful elements of the existing Example App and fixed any issues affecting UX. 
  - Used 1st version of the Juno UI design document to gather ideas and guide some decision making.
  - Used as many Juno UI components as possible (currently **68%**). Some components didn't need to be used as for example, they're for manual scaffolding, interchangeable etc. Some decided not to use, notes below.
- Completed a proposal:
  - Currently in feedback stage, need to demo the proposal, get feedback and make remaining decisions.
  - Improvements in more detail will be documented later. 

**Components Used**

- Non-Deprecated External Components * 56/82 components used 68%:
  - [x] packages/ui-components/src/components/AppShell
  - [x] packages/ui-components/src/components/AppShellProvider
  - [x] packages/ui-components/src/components/Badge
  - [x] packages/ui-components/src/components/Box
  - [x] packages/ui-components/src/components/Breadcrumb
  - [x] packages/ui-components/src/components/BreadcrumbItem
  - [x] packages/ui-components/src/components/Button
  - [x] packages/ui-components/src/components/ButtonRow
  - [x] packages/ui-components/src/components/Checkbox
  - [x] packages/ui-components/src/components/CheckboxGroup
  - [ ] packages/ui-components/src/components/**Code** - no use case
  - [x] packages/ui-components/src/components/CodeBlock
  - [x] packages/ui-components/src/components/ComboBox
  - [x] packages/ui-components/src/components/ComboBoxOption
  - [x] packages/ui-components/src/components/Container
  - [ ] packages/ui-components/src/components/**ContentAreaToolbar** - don’t want to use
  - [x] packages/ui-components/src/components/DataGrid
  - [x] packages/ui-components/src/components/DataGridCell
  - [ ] packages/ui-components/src/components/**DataGridCheckboxCell** - no use case
  - [ ] packages/ui-components/src/components/**DataGridFoot** - no use case
  - [x] packages/ui-components/src/components/DataGridHeadCell
  - [x] packages/ui-components/src/components/DataGridRow
  - [x] packages/ui-components/src/components/DataGridToolbar
  - [x] packages/ui-components/src/components/DateTimePicker
  - [x] packages/ui-components/src/components/Form
  - [ ] packages/ui-components/src/components/**FormattedText** - ?
  - [x] packages/ui-components/src/components/FormRow
  - [x] packages/ui-components/src/components/FormSection
  - [ ] packages/ui-components/src/components/**Grid**
  - [ ] packages/ui-components/src/components/**GridColumn**
  - [ ] packages/ui-components/src/components/**GridRow**
  - [x] packages/ui-components/src/components/Icon
  - [ ] packages/ui-components/src/components/**InputGroup** - ?
  - [ ] packages/ui-components/src/components/**IntroBox** - ?
  - [x] packages/ui-components/src/components/JsonViewer 
  - [ ] packages/ui-components/src/components/**Label** -?
  - [ ] packages/ui-components/src/components/**LoadingIndicator** - don’t want to use
  - [x] packages/ui-components/src/components/MainTabs
  - [x] packages/ui-components/src/components/Message
  - [x] packages/ui-components/src/components/Modal
  - [x] packages/ui-components/src/components/ModalFooter
  - [ ] packages/ui-components/src/components/**NativeSelect** - using Select instead
  - [ ] packages/ui-components/src/components/**NativeSelectOption** - using Select instead
  - [ ] packages/ui-components/src/components/**NativeSelectOptionGroup** - using Select instead
  - [x] packages/ui-components/src/components/PageFooter
  - [x] packages/ui-components/src/components/PageHeader
  - [x] packages/ui-components/src/components/Pagination
  - [x] packages/ui-components/src/components/Panel
  - [x] packages/ui-components/src/components/PanelBody
  - [x] packages/ui-components/src/components/PanelFooter
  - [x] packages/ui-components/src/components/Pill
  - [x] packages/ui-components/src/components/PopupMenu
  - [x] packages/ui-components/src/components/PortalProvider
  - [x] packages/ui-components/src/components/Radio
  - [x] packages/ui-components/src/components/RadioGroup
  - [x] packages/ui-components/src/components/SearchInput
  - [ ] packages/ui-components/src/components/**SecretText** - no use case
  - [x] packages/ui-components/src/components/Select
  - [ ] packages/ui-components/src/components/SelectDivider
  - [x] packages/ui-components/src/components/SelectOption
  - [ ] packages/ui-components/src/components/**ShadowRoot** - no use case
  - [ ] packages/ui-components/src/components/**SideNavigation** - using TopNavigation instead
  - [ ] packages/ui-components/src/components/**SideNavigationItem** - using TopNavigation instead
  - [x] packages/ui-components/src/components/Spinner
  - [x] packages/ui-components/src/components/Stack
  - [ ] packages/ui-components/src/components/**StyleProvider**
  - [x] packages/ui-components/src/components/Switch
  - [x] packages/ui-components/src/components/Tab - should use TopNavigation and not Tabs
  - [x] packages/ui-components/src/components/TabList - should use TopNavigation and not Tabs
  - [ ] packages/ui-components/src/components/**TabNavigation** - should use TopNavigation and not Tabs
  - [ ] packages/ui-components/src/components/**TabNavigationItem** - should use TopNavigation and not Tabs
  - [x] packages/ui-components/src/components/TabPanel - should use TopNavigation and not Tabs
  - [ ] packages/ui-components/src/components/**Tabs**
  - [x] packages/ui-components/src/components/Textarea
  - [x] packages/ui-components/src/components/TextInput
  - [x] packages/ui-components/src/components/ThemeToggle
  - [x] packages/ui-components/src/components/Toast
  - [x] packages/ui-components/src/components/Tooltip
  - [x] packages/ui-components/src/components/TooltipContent
  - [x] packages/ui-components/src/components/TooltipTrigger
  - [ ] packages/ui-components/src/components/**TopNavigation** - using Tabs for now
  - [ ] packages/ui-components/src/components/**TopNavigationItem** - using Tabs for now

Internal (8)
  - [ ] packages/ui-components/src/components/AppBody
  - [ ] packages/ui-components/src/components/ContentContainer
  - [x] packages/ui-components/src/components/ContentHeading
  - [ ] packages/ui-components/src/components/HeaderContainer
  - [ ] packages/ui-components/src/components/MainContainer
  - [ ] packages/ui-components/src/components/MainContainerInner (No Story)
  - [ ] packages/ui-components/src/components/Navigation
  - [ ] packages/ui-components/src/components/NavigationItem

Not Exported (but in Storybook under Forms) (1)
  - [ ] packages/ui-components/src/components/FormHint
