### ISSUE TITLE
[Task](greenhouse): improve initialFilters Assignment to Conditionally Include support_group Key

### ISSUE THREAD

**Issue by ArtieReus** [cloudoperators/juno#611]
**Task Description**
Currently, the code in Greenhouse assigns the support_group key in appProps.initialFilters based on the existence of authData?.parsed?.supportGroups. Second Supernova due to initialFilter being set as { "support_group": "undefined" } when supportGroups was missing or incorrectly retrieved led to unhandled exceptions due to the unexpected value of undefined for support_group.

**Background**

- Greenhouse previously ran in production with an older version until it was updated on 13.11.24, when the pipeline was decoupled. In the older Greenhouse version, extensions (such as Supernova and Doop) retrieved the support_group directly from their own authentication objects and applied it as a filter.
- In the new Greenhouse version, the support_group is extracted from the authentication object of the logged-in user. This support_group is then applied as the initialFilter for relevant plugins.
- However, users from CCLoud have encountered issues in Supernova due to initialFilter being set as { "support_group": "undefined" } when supportGroups was missing or incorrectly retrieved. This led to Supernova encountering unhandled exceptions due to the unexpected value of undefined for support_group.

**Sub-tasks**

- [x] The support_group key is added only if supportGroups exists and is an array in greenhouse. #608
- [x] If supportGroups is not defined or not an array, support_group is omitted from initialFilters in greenhouse. #608
- [x] Update Supernova to handle unexpected configurations in initialFilters by ignoring entries that do not fit the expected structure. #610
