### ISSUE TITLE
[EPIC](ui): Finalize v2 of operator dashboard UI components

### ISSUE THREAD

**Issue by edda** [cloudoperators/juno#62]
Develop missing v2 components and fix bugs.

- [x] #64 
- [x] #65
- [x] #66 
- [x] #55 
- [x] #129 
- [x] #99
- [x] #169 
- [x] #328 
- [x] TopNavigation position should be fixed and not move on scroll
- [x] #237 
- [x] #529
- [ ] #73 
- [x] #167 
- [ ] #721 
- [ ] Stack: add spacing boolean prop to add standard gap spacing value (similar to the ones on the Container component)
- [ ] DataGrid Row hover/active state (plus prop to toggle hover/active behaviour)

**Prep for major version breaking changes:**
- [ ] Look into potentially replacing Material icons with [Lucide icons](https://lucide.dev) and use [Lucide React's feature of dynamic imports](https://lucide.dev/guide/packages/lucide-react#dynamic-icon-component)
- [ ] Package size optimization: 
     - [ ] don't deliver fonts with package, find other ways to load the fonts
     - [ ] look into webcomponent templates to load the styles once on the page
- [x] #739
- [ ] Headless UI upgrade to v2.x (see also https://github.com/cloudoperators/juno/issues/529#issuecomment-2548988298)
- [ ] #723 

Bugs:
- [x] #67 
- [x] #176 
- [x] #506
- [x] #68

**Sprint 25.03:**
- [ ] #626 
- [x] #165
- [x] #516 
- [x] #810

**Comment by edda** [comment]
Open topics moved to #1000
