### ISSUE TITLE
[Task](Example): Example app mock data static change

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#631]
**Task Description**
We need to replace Juno-utils mock data from example app and replace with a 

**Sub-tasks**

- [x] We need to remove dependency of mock calls to Juno-utils in example app.
- [x] Create a static json file that responsible for data inside example app.
- [x] Replace all fetches calls with mock.

**Related Issues**
#446
