### ISSUE TITLE
[Task](internal): PR Manifesto

### ISSUE THREAD

**Issue by guoda-puidokaite** [cloudoperators/juno#642]
**Task Description**

To make our PR process more stream-lined, in this task we should create a short PR manifesto with agreed guidelines.

**Sub-tasks**

- [x] Create GH documentation with 5-10 manifesto points
- [ ] Before merging, ask team to review and contribute
- [x] Add link in PR template
