### ISSUE TITLE
[Task](ui): Change imports from deprecated Javascript components to Typescript and tidy up

### ISSUE THREAD

**Issue by guoda-puidokaite** [cloudoperators/juno#645]
### Task Description

When all components in @cloudoperators/juno-ui-components have been migrated to Typescript, we should swap over any remaining deprecated imports to the new migrated ones. After all, delete all migrated Javascript components from deprecated_js.

**List of potential dependencies**

- All components depending on `Portal` should be migrated before making the change. Last component to be merged is `DateTimePicker` https://github.com/cloudoperators/juno/issues/227.

**Sub-tasks**

- [x] Make sure that all migrated components import Typescript components instead of deprecated Javascript ones (especially Portal and AppShellProvider).
- [x] Change `index.js` in `AppShellProvider` to `index.ts`.
- [x] Delete all migrated components from `deprecated_js`.
- [ ] Check `Storybook`
- [ ] Test Supernova, Elektra
- [x] Fix all errors related to `npm run typecheck`
- [x] Check if `npm run build` is working (note: errors already existed before, need to fix in another ticket)
- [x] Check that `npm run lint` is working correctly and fix all `tslint` errors

**Related Issues**
- #168

**Comment by guoda-puidokaite** [comment]
**Tested Supernova and Elektra Key Manager** with @ArtieReus, focusing on `Portal`-related functionality

**Supernova** ✅

- Clicked on the "Silence" button from the alerts list and from the alert details view
  -  then clicked on the silence duration dropdown to verify that everything is visible and stacked properly on top of each other
- Checked that the `Panel` header is visible and doesn't disappear underneath the `PageHeader`
- Scrolled down to make the content disappear underneath the `PageHeader`

<img width="1435" alt="Screenshot 2024-12-11 at 09 59 43" src="https://github.com/user-attachments/assets/37fb141e-5d8c-4de3-93c3-7e30614ff1bb">

<img width="1432" alt="Screenshot 2024-12-11 at 10 02 08" src="https://github.com/user-attachments/assets/b116c2a6-7328-4a57-8e5e-1ede2f521949">

<img width="1436" alt="Screenshot 2024-12-11 at 10 02 51" src="https://github.com/user-attachments/assets/d80caa16-bfa4-4707-bab8-aba155f6c1e3">

**Elektra Key Manager** ✅

- Opened a `Panel` to see that it opens correctly above the Elektra `PageHeader`
- Tested the `DateTimePicker`
- Tested `Select`

<img width="1316" alt="Screenshot 2024-12-11 at 09 55 22" src="https://github.com/user-attachments/assets/b2da760e-3b11-4368-9314-b9ca71534bda">

<img width="1313" alt="Screenshot 2024-12-11 at 09 55 33" src="https://github.com/user-attachments/assets/4c4e04b0-1475-4eb4-894c-c3a73cd6a708">

<img width="342" alt="Screenshot 2024-12-11 at 09 55 55" src="https://github.com/user-attachments/assets/afd8ffe4-01fb-4f79-904b-64911f2e8c16">

<img width="368" alt="Screenshot 2024-12-11 at 09 57 25" src="https://github.com/user-attachments/assets/ac90d1f4-d57c-47ce-ae74-35dda02a0b5c">

CC: @edda @barsukov @andypf
