### ISSUE TITLE
[Task](ui-components): Typescript children default value removal and also add default value if necessery for other properties

### ISSUE THREAD

**Issue by barsukov** [cloudoperators/juno#678]
**Task Description**
...

**Sub-tasks**

- [x] Delete children = null everywhere 
- [x] See if children are of type ReactNode (**Update**: Most are, added rest to [type check ticket](https://github.com/cloudoperators/juno/issues/664))
- [ ] Add default value if necessery for other properties (**Update**: Not done)
  - [x] Instead fixed vitest configuration. Read [update](https://github.com/cloudoperators/juno/issues/678#issuecomment-2601917112)).

**Related Issues**
Link to related issues or tasks, if any.

**Additional Context**
Add any other context or information here.

**Comment by barsukov** [comment]
https://dev.to/bytebodger/default-props-in-react-typescript-2o5o
