### ISSUE TITLE
[Task](ui): address errors and warnings during testing

### ISSUE THREAD

**Issue by andypf** [cloudoperators/juno#695]
Multiple errors related to the Flatpickr locale and warnings about act are appearing while running tests in ui-components. It seems these warnings originate from packages inside node_modules, which is unexpected since Vitest typically ignores this folder by default. This behavior needs investigation.

Regarding Flatpickr, the issue appears to be a real bug. According to the error, the locale parameter is missing. We use `flatpickr` in the DateTimePicker component. Interestingly, this error does not cause the test to fail, which is unusual and should be looked into.

## Sub-tasks

- [ ] Fix the Flatpickr error: Ensure the locale parameter is correctly set in the DateTimePicker component to resolve the missing locale issue.
- [ ] Fix the act warning: Investigate and address the source of the act warning, especially if it originates from dependencies in node_modules.
- [ ] Ensure a clean test suite: The test suite should run without any warnings or errors, ensuring a clean and stable testing environment.

## Additional Context
**flatpickr**
```bash
Error: flatpickr: invalid locale undefined
    at setupLocale (/workspace/co-juno/node_modules/flatpickr/dist/flatpickr.js:2060:42)
    at init (/workspace/co-juno/node_modules/flatpickr/dist/flatpickr.js:640:13)
    at FlatpickrInstance (/workspace/co-juno/node_modules/flatpickr/dist/flatpickr.js:2637:9)
    at _flatpickr (/workspace/co-juno/node_modules/flatpickr/dist/flatpickr.js:2656:35)
    at Proxy.flatpickr (/workspace/co-juno/node_modules/flatpickr/dist/flatpickr.js:2683:20)
    at createFlatpickrInstance (/workspace/co-juno/packages/ui-components/src/components/DateTimePicker/DateTimePicker.component.tsx:291:54)
    at /workspace/co-juno/packages/ui-components/src/components/DateTimePicker/DateTimePicker.component.tsx:302:5
    at commitHookEffectListMount (/workspace/co-juno/node_modules/react-dom/cjs/react-dom.development.js:23189:26)
    at commitPassiveMountOnFiber (/workspace/co-juno/node_modules/react-dom/cjs/react-dom.development.js:24970:11)
    at commitPassiveMountEffects_complete (/workspace/co-juno/node_modules/react-dom/cjs/react-dom.development.js:24930:9)
```
**act warning**
```bash
Warning: An update to DateTimePicker inside a test was not wrapped in act(...).

When testing, code that causes React state updates should be wrapped into act(...):

act(() => {
  /* fire events that update state */
});
/* assert on the output */

This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
    at DateTimePicker (/workspace/co-juno/packages/ui-components/src/components/DateTimePicker/DateTimePicker.component.tsx:68:3)
```

**Comment by barsukov** [comment]
I would add this to comtinue on this ticket, this leftover warnings that we need to work on:
1) 
"Warning: TabPanel: Support for defaultProps will be rem
│ oved from function components in a future major release
│ . Use JavaScript default parameters instead.
│     at TabPanel (/Users/wowa/work/juno/node_modules/rea
│ ct-tabs/lib/components/TabPanel.js:42:24)
│     at TabPanel (/Users/wowa/work/juno/packages/ui-comp
│ onents/src/components/TabPanel/TabPanel.component.tsx:5
│ :21)"
2)
Warning: An update to Float inside a test was not wrapp
│ ed in act(...).
│ 
│ When testing, code that causes React state updates shou
│ ld be wrapped into act(...):
│ 
│ act(() => {
│   /* fire events that update state */
│ });
│ /* assert on the output */
│ 
│ This ensures that you're testing the behavior the user 
│ would see in the browser. Learn more at https://reactjs
│ .org/link/wrap-tests-with-act
│     at file:///Users/wowa/work/juno/node_modules/@headl
│ essui-float/react/dist/headlessui-float.mjs:1102:22
│     at s (file:///Users/wowa/work/juno/node_modules/@he
│ adlessui/react/dist/internal/open-closed.js:1:263)
│     at Me (file:///Users/wowa/work/juno/node_modules/@h
│ eadlessui/react/dist/components/menu/menu.js:1:3529)
│     at ContextMenu (/Users/wowa/work/juno/packages/ui-c
│ omponents/src/components/ContextMenu/ContextMenu.compon
│ ent.tsx:30:3)
3)
 Warning: FormattedText: Support for defaultProps will b
│ e removed from function components in a future major re
│ lease. Use JavaScript default parameters instead.
│     at FormattedText (/Users/wowa/work/juno/packages/ui
│ -components/src/components/FormattedText/FormattedText.
│ component.tsx:6:3)
4)
 Warning: TabList: Support for defaultProps will be remo
│ ved from function components in a future major release.
│  Use JavaScript default parameters instead.
│     at TabList (/Users/wowa/work/juno/node_modules/reac
│ t-tabs/lib/components/TabList.js:29:24)
│     at TabList (/Users/wowa/work/juno/packages/ui-compo
│ nents/src/components/TabList/TabList.component.tsx:29:2
│ 0)
│ 
5)
Warning: Tab: Support for defaultProps will be removed 
│ from function components in a future major release. Use
│  JavaScript default parameters instead.
│     at Tab (/Users/wowa/work/juno/node_modules/react-ta
│ bs/lib/components/Tab.js:56:35)
│     at Tab (/Users/wowa/work/juno/packages/ui-component
│ s/src/components/Tab/Tab.component.tsx:26:16)
6)
 stderr | src/components/NativeSelectOptionGroup/NativeS
│ electOptionGroup.test.tsx > NativeSelectOptionGroup > C
│ hildren Rendering > renders with mixed children types
│ Warning: validateDOMNesting(...): <span> cannot appear 
│ as a child of <optgroup>.
│     at span
│     at optgroup
│     at NativeSelectOptionGroup (/Users/wowa/work/juno/p
│ ackages/ui-components/src/components/NativeSelectOption
│ Group/NativeSelectOptionGroup.component.tsx:4:3)

7)
│ stderr | src/components/Panel/Panel.test.tsx > Panel > 
│ Events > double-click on close button fires onClose han
│ dler twice
│ usePortalRef must be called inside a PortalProvider. Yo
│ u are probably using a component that renders a portal,
│  e.g. Modal or Select. Make sure your app is wrapped in
│  an AppShellProvider. Alternatively, a PortalProvider c
│ an be included manually.
8)
 stderr | src/components/Panel/Panel.test.tsx > Panel > 
│ Events > on click on close button when panel is already
│  closed
│ usePortalRef must be called inside a PortalProvider. Yo
│ u are probably using a component that renders a portal,
│  e.g. Modal or Select. Make sure your app is wrapped in
│  an AppShellProvider. Alternatively, a PortalProvider c
│ an be included manually.
│

**Comment by gjaskiewicz** [comment]
Unfortunately I wasn't able to create a draft PR, but I checked how to get rid of Tab, TabList and Tabs warnings in tests and this could be done by updating react-tabs npm to:
"react-tabs": "6.1.0"
