### ISSUE TITLE
[EPIC](docs): Open source documentation

### ISSUE THREAD

**Issue by edda** [cloudoperators/juno#71]
Make our statically built documentation available in the context of the cloudoperators org.

- [x] #59
- [x] Research how to publish PRs from storybook in github pages
- [x] #193 
- [ ] Hugo based documentation
- [ ] Asset server (?)
- [ ] Make all of the above accessible via the gh-page of the Juno repo
