### ISSUE TITLE
[EPIC](website) Design and create marketing website

### ISSUE THREAD

**Issue by edda** [cloudoperators/juno#83]
The ORA project needs a simple marketing website with high-level information about the project, as well as links to our public repos, documentation, etc.

- [x] Design the website
- [x] Develop the website using a static site generator, including Github workflow to publish as github page
- [x] Design logo for new name ApeiroRA
- [x] Verify that licenses of imagery from Brandtools and Poppins open source font allow use in our context
- [x] Get final information about legal requirements for this type of website (impressum, copyright notice, what else?) and add necessary pieces to the website
- [x] Finalize website content
- [x] Request DNS name and assign to github page

Bugs:
- [x] Hamburger menu is not clickable in mobile view (it looks like this is caused by the `scroll-container` overlaying the hamburger and preventing the click
- [x] Some of the text on the landing page can't be selected (in the "our mission" and the "open source" section): this is caused by the `hero_image_css` div overlaying that part of the page

**Comment by MartinS-git** [comment]
Done with PR: https://github.com/apeirora/website/compare/mobile-fixing?expand=1
